/// Generated file. Do not edit.
/// This file is generated by the iFlutter

// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars
class AssetsRes {
  static const String PLUGIN_NAME = 'tabornski_sos_prirocnik_frontend';
  static const String PLUGIN_VERSION = '1.0.0+1';
  static const String RSK_LOGO = 'assets/images/rsk_logo.png';
  static const String SINGLE_SEPARATOR_FOREST = 'assets/images/single_separator_forest.png';
}
