/// Generated file. Do not edit.
/// This file is generated by the iFlutter

// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars
class FontRes {
  FontRes._();

  static const String CUSTOMICONS = 'CustomIcons';
  static const String JETBRAINSMONO_BOLD = 'JetBrainsMono-Bold';
  static const String JETBRAINSMONO_REGULAR = 'JetBrainsMono-Regular';
}
